# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Monica"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "Monica - Perfect Hugo theme for any blog site."
homepage = "https://www.tomaschudjak.com"
tags = ["blog","fast","multilingual","customizable","typography"]
features = ["customizable theme", "multilingual","seo","open graph","twitter cards", "google analytics", "google adsense","authors","related posts","previous and next posts","editable sidebar","reading time","categories","tags"]
min_version = "0.41"

[author]
  name = "Tomas Chudjak"
  homepage = "https://www.tomaschudjak.com"
